// Code generated by tron. Place config helpers here.
package config

import (
	"github.com/spf13/viper"
)

func ImgPath() string {
	return viper.GetString(ImagesPath)
}

func DBPath() string {
	return viper.GetString(DatabasePath)
}
