version: '3'
services:
  cloudsuny-backend:
    image: golang:1.15-alpine
    volumes:
      - ./backend/:/app
      - ./data/db/:/db/
      - ./data/images/:/images/
    working_dir: /app/cmd/cloudsuny/
    command: [
        "/bin/sh",
        "-c",
        "apk update && apk add --no-cache ca-certificates gcc musl-dev && ./run.sh"
      ]
    environment:
      - SERVER_HTTP_PORT=8080
      - SERVER_CERT=
      - SERVER_KEY=

      - LOGGER_LEVEL=debug
      - LOGGER_NAMESPACE=dev
      - LOGGER_COLLECTOR_URL=

      - PATH_DB=/db/database.db
      - PATH_IMG=/images
    ports:
      - 8080:8080

  cloudsuny-frontend:
    image: node:12.8-alpine
    volumes:
      - ./frontend/:/app
    working_dir: /app/
    command: [
        "/bin/sh",
        "-c",
        "yarn install && yarn serve"
      ]
    ports:
      - 3000:8080
