version: '3'
services:
  cloudsuny-backend:
    image: golang:1.15-alpine
    volumes:
      - ./backend/:/app
      - ./data/db/:/db/
      - ./data/images/:/images/
    working_dir: /app
    command: ["/bin/sh", "-c", "apk add --no-cache make ca-certificates gcc musl-dev && make run-local"]
    ports:
      - 8080:8080 # public http
      - 8081:8081 # public grpc
      - 8082:8082 # admin http

#  cloudsuny-frontend:
#    image: node:12.8-alpine
#    volumes:
#      - ./frontend/:/app
#    working_dir: /app/
#    command: [
#        "/bin/sh",
#        "-c",
#        "yarn install && yarn serve"
#      ]
#    ports:
#      - 3000:8080
