version: '3'
services:
  cloudsuny-backend:
    image: golang:1.15-alpine
    volumes:
      - ./cloudsuny/:/app
      - ./data/db/:/db/
      - ./data/images/:/images/
      - ./.git:/app/.git
      - go-build-cache:/root/.cache/go-build
    working_dir: /app
    command: ["/bin/sh", "-c", "apk add --no-cache make git ca-certificates gcc musl-dev && make run"]
    environment:
      - NAMESPACE=dev
    ports:
      - 8080:8080 # public http
      - 8081:8081 # public grpc
      - 8082:8082 # admin http

  cloudsuny-frontend:
    image: node:12.8-alpine
    volumes:
      - ./frontend/:/app
    working_dir: /app/
    environment:
      - SERVER_HOST=http://cloudsuny-backend:8080
    command: [
        "/bin/sh",
        "-c",
        "yarn install && yarn serve --port 3000"
      ]
    ports:
      - 3000:3000

volumes:
  go-build-cache:
