version: '3'
services:
  cloudsuny-backend:
    image: golang:1.15-alpine
    volumes:
      - ./cloudsuny/:/app
      - ./data/db/:/db/
      - ./.git:/app/.git
      - ./data/images/:/images/
    working_dir: /app
    command: ["/bin/sh", "-c", "apk add --no-cache make git ca-certificates gcc musl-dev && make run local-config-enabled"]
    ports:
      - 8080:8080 # public http
      - 8081:8081 # public grpc
      - 8082:8082 # admin http

  cloudsuny-frontend:
    image: node:12.8-alpine
    volumes:
      - ./frontend/:/app
    working_dir: /app/
    command: [
        "/bin/sh",
        "-c",
        "yarn install && yarn serve"
      ]
    ports:
      - 3000:8080
