// Code generated by tron. You must modify it.

package badges

import (
	"context"

	"github.com/loghole/tracing/tracelog"
	transport "github.com/loghole/tron/transport"

	"github.com/lissteron/cloudsuny/internal/app/domain"
	badgesV1 "github.com/lissteron/cloudsuny/pkg/badges/v1"
)

type BadgeService interface {
	Create(ctx context.Context, badge *domain.Badge) (*domain.Badge, error)
	Update(ctx context.Context, badge *domain.Badge) (*domain.Badge, error)
}

type Implementation struct {
	badgesV1.UnimplementedBadgesServer
	service BadgeService
	logger  tracelog.Logger
}

func NewImplementation(service BadgeService, logger tracelog.Logger) *Implementation {
	return &Implementation{
		service: service,
		logger:  logger,
	}
}

// GetDescription is a simple alias to the ServiceDesc constructor.
// It makes it possible to register the service implementation @ the server.
func (i *Implementation) GetDescription() transport.ServiceDesc {
	return badgesV1.NewBadgesServiceDesc(i)
}
