// Code generated by tron. You must modify it.

package badges

import (
	context "context"

	badgesV1 "github.com/lissteron/cloudsuny/pkg/badges/v1"
	"github.com/lissteron/cloudsuny/pkg/types/v1"
)

func (i *Implementation) Update(
	ctx context.Context,
	req *badgesV1.UpdateReq,
) (resp *badgesV1.UpdateResp, err error) {
	if err := req.Validate(); err != nil {
		return nil, err
	}

	result, err := i.service.Update(ctx, req.ToDomain())
	if err != nil {
		return nil, err
	}

	resp = &badgesV1.UpdateResp{
		Data: types.BadgeFromDomain(result),
	}

	return resp, nil
}
