// Code generated by tron. You must modify it.

package users

import (
	"context"

	"github.com/loghole/tracing/tracelog"
	transport "github.com/loghole/tron/transport"

	"github.com/lissteron/cloudsuny/internal/app/domain"
	usersV1 "github.com/lissteron/cloudsuny/pkg/users/v1"
)

type CreateUser interface {
	Do(ctx context.Context, user *domain.User) (*domain.User, error)
}

type ListUsers interface {
	Do(ctx context.Context) ([]*domain.User, error)
}

type Implementation struct {
	usersV1.UnimplementedUsersServer
	create CreateUser
	list   ListUsers
	logger tracelog.Logger
}

func NewImplementation(create CreateUser, list ListUsers, logger tracelog.Logger) *Implementation {
	return &Implementation{
		create: create,
		list:   list,
		logger: logger,
	}
}

// GetDescription is a simple alias to the ServiceDesc constructor.
// It makes it possible to register the service implementation @ the server.
func (i *Implementation) GetDescription() transport.ServiceDesc {
	return usersV1.NewUsersServiceDesc(i)
}
