// Code generated by tron. You must modify it.

package users

import (
	context "context"

	usersV1 "github.com/lissteron/cloudsuny/pkg/users/v1"
)

func (i *Implementation) ListWithBadges(
	ctx context.Context,
	req *usersV1.ListWithBadgesReq,
) (resp *usersV1.ListWithBadgesResp, err error) {
	result, err := i.list.Do(ctx)
	if err != nil {
		return nil, err
	}

	resp = &usersV1.ListWithBadgesResp{
		Data: make([]*usersV1.User, 0, len(result)),
	}

	for _, user := range result {
		resp.Data = append(resp.Data, usersV1.UserFromDomain(user))
	}

	return resp, nil
}
