// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: users.proto

package users

import (
	"context"

	desc "github.com/lissteron/cloudsuny/pkg/users/v1"
)

func (i *Implementation) ListWithBadges(
	ctx context.Context,
	req *desc.ListUsersWithBadgesReq,
) (resp *desc.ListUsersWithBadgesResp, err error) {
	result, err := i.list.Do(ctx)
	if err != nil {
		i.logger.Errorf(ctx,"list users with badges failed: %v", err)

		return nil, err
	}

	resp = &desc.ListUsersWithBadgesResp{
		Data: make([]*desc.User, 0, len(result)),
	}

	for _, user := range result {
		resp.Data = append(resp.Data, desc.UserFromDomain(user))
	}

	return resp, nil
}
