// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: users.proto

package users

import (
	"context"

	"github.com/loghole/tracing/tracelog"
	"github.com/utrack/clay/v2/transport"

	"github.com/lissteron/cloudsuny/internal/app/domain"
	desc "github.com/lissteron/cloudsuny/pkg/users/v1"
)

type CreateUser interface {
	Do(ctx context.Context, user *domain.User) (*domain.User, error)
}

type ListUsers interface {
	Do(ctx context.Context) ([]*domain.User, error)
}

type Implementation struct {
	create CreateUser
	list   ListUsers
	logger tracelog.Logger
}

// NewUsers create new Implementation
func NewUsers(create CreateUser, list ListUsers, logger tracelog.Logger) *Implementation {
	return &Implementation{
		create: create,
		list:   list,
		logger: logger,
	}
}

// GetDescription is a simple alias to the ServiceDesc constructor.
// It makes it possible to register the service implementation @ the server.
func (i *Implementation) GetDescription() transport.ServiceDesc {
	return desc.NewUsersServiceDesc(i)
}
