// Code generated by tron. You must modify it.

package users

import (
	context "context"

	"github.com/lissteron/simplerr"

	usersV1 "github.com/lissteron/cloudsuny/pkg/users/v1"
)

func (i *Implementation) Create(
	ctx context.Context,
	req *usersV1.CreateReq,
) (resp *usersV1.CreateResp, err error) {
	if err := req.Validate(); err != nil {
		return nil, simplerr.Wrap(err, "invalid request")
	}

	result, err := i.service.Create(ctx, req.ToDomain())
	if err != nil {
		return nil, err
	}

	resp = &usersV1.CreateResp{
		Data: usersV1.UserFromDomain(result),
	}

	return resp, nil
}
