// Code generated by tron. You must modify it.

package users

import (
	"context"

	"github.com/loghole/tracing/tracelog"
	transport "github.com/loghole/tron/transport"

	"github.com/lissteron/cloudsuny/internal/app/domain"
	usersV1 "github.com/lissteron/cloudsuny/pkg/users/v1"
)

const (
	defaultLimit = 50
)

type UserService interface {
	Create(ctx context.Context, user *domain.User) (*domain.User, error)
	List(ctx context.Context, limit, offset uint64) (*domain.UserListResult, error)
	Delete(ctx context.Context, userID string) error
}

type Implementation struct {
	usersV1.UnimplementedUsersServer
	service UserService
	logger  tracelog.Logger
}

func NewImplementation(service UserService, logger tracelog.Logger) *Implementation {
	return &Implementation{
		service: service,
		logger:  logger,
	}
}

// GetDescription is a simple alias to the ServiceDesc constructor.
// It makes it possible to register the service implementation @ the server.
func (i *Implementation) GetDescription() transport.ServiceDesc {
	return usersV1.NewUsersServiceDesc(i)
}
