// Code generated by tron. You must modify it.

package users

import (
	context "context"

	usersV1 "github.com/lissteron/cloudsuny/pkg/users/v1"
)

func (i *Implementation) ListWithBadges(
	ctx context.Context,
	req *usersV1.ListWithBadgesReq,
) (resp *usersV1.ListWithBadgesResp, err error) {
	if req.Limit == 0 {
		req.Limit = defaultLimit
	}

	result, err := i.service.List(ctx, req.Limit, req.Offset)
	if err != nil {
		return nil, err
	}

	resp = &usersV1.ListWithBadgesResp{
		Data:    usersV1.UserListFromDomain(result.List),
		Total:   result.Total,
		Count:   result.Count,
		Skipped: result.Skipped,
	}

	return resp, nil
}
