// Code generated by tron1.1.0. DO NOT EDIT.

package badges

import (
	context "context"
	runtime "github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	transport "github.com/loghole/tron/transport"
	grpc "google.golang.org/grpc"
)

// BadgesServiceDesc is description for the BadgesServer.
type BadgesServiceDesc struct {
	svc BadgesServer
}

func NewBadgesServiceDesc(i BadgesServer) transport.ServiceDesc {
	return &BadgesServiceDesc{svc: i}
}

func (d *BadgesServiceDesc) RegisterGRPC(s *grpc.Server) {
	RegisterBadgesServer(s, d.svc)
}

func (d *BadgesServiceDesc) RegisterHTTP(mux *runtime.ServeMux) {
	RegisterBadgesHandlerServer(context.Background(), mux, d.svc)
}

func (d *BadgesServiceDesc) SwaggerDef() []byte {
	return []byte(`{
  "swagger": "2.0",
  "info": {
    "title": "badges.proto",
    "version": "version not set"
  },
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/api/v1/badge/create": {
      "post": {
        "operationId": "Badges_Create",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/badges.v1.CreateResp"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/google.rpc.Status"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/badges.v1.CreateReq"
            }
          }
        ],
        "tags": [
          "Badges"
        ]
      }
    },
    "/api/v1/badge/update": {
      "post": {
        "operationId": "Badges_Update",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/badges.v1.UpdateResp"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/google.rpc.Status"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/badges.v1.UpdateReq"
            }
          }
        ],
        "tags": [
          "Badges"
        ]
      }
    }
  },
  "definitions": {
    "badges.v1.CreateReq": {
      "type": "object",
      "properties": {
        "user_id": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "point": {
          "$ref": "#/definitions/types.v1.Point"
        }
      }
    },
    "badges.v1.CreateResp": {
      "type": "object",
      "properties": {
        "data": {
          "$ref": "#/definitions/types.v1.Badge"
        }
      }
    },
    "badges.v1.UpdateReq": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "point": {
          "$ref": "#/definitions/types.v1.Point"
        }
      }
    },
    "badges.v1.UpdateResp": {
      "type": "object",
      "properties": {
        "data": {
          "$ref": "#/definitions/types.v1.Badge"
        }
      }
    },
    "google.protobuf.Any": {
      "type": "object",
      "properties": {
        "typeUrl": {
          "type": "string"
        },
        "value": {
          "type": "string",
          "format": "byte"
        }
      }
    },
    "google.rpc.Status": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        },
        "details": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/google.protobuf.Any"
          }
        }
      }
    },
    "types.v1.Badge": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "user_id": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "point": {
          "$ref": "#/definitions/types.v1.Point"
        },
        "created_at": {
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "types.v1.Point": {
      "type": "object",
      "properties": {
        "x": {
          "type": "number",
          "format": "double"
        },
        "y": {
          "type": "number",
          "format": "double"
        }
      }
    }
  }
}
`)
}
