// Generated by tron. You must modify it.
package auth

import (
	context "context"

	authV1 "github.com/lissteron/cloudsuny/pkg/auth/v1"
)

func (i *Implementation) SignIn(
	ctx context.Context,
	req *authV1.SignInReq,
) (resp *authV1.SignInResp, err error) {
	if err := req.Validate(); err != nil {
		return nil, err
	}

	session, err := i.service.SignIn(ctx, req.Login, req.Password)
	if err != nil {
		return nil, err
	}

	if err := i.setGRPCCookie(ctx, session.Token, false); err != nil {
		return nil, err
	}

	return &authV1.SignInResp{}, nil
}
