// Generated by tron. You must modify it.
package auth

import (
	context "context"

	authV1 "github.com/lissteron/cloudsuny/pkg/auth/v1"
)

func (i *Implementation) SignOut(
	ctx context.Context,
	req *authV1.SignOutReq,
) (resp *authV1.SignOutResp, err error) {
	if err := i.service.SignOut(ctx, i.readGRPCCookie(ctx)); err != nil {
		return nil, err
	}

	if err := i.setGRPCCookie(ctx, "", true); err != nil {
		return nil, err
	}

	return &authV1.SignOutResp{}, nil
}
