// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: badges.proto

package badges

import (
	"github.com/loghole/tracing/tracelog"

	"github.com/lissteron/cloudsuny/internal/app/domain"
	desc "github.com/lissteron/cloudsuny/pkg/badges/v1"

	"context"

	"github.com/utrack/clay/v2/transport"
)

type CreateBadge interface {
	Do(ctx context.Context, badge *domain.Badge) (*domain.Badge, error)
}

type UpdateBadge interface {
	Do(ctx context.Context, badge *domain.Badge) (*domain.Badge, error)
}

type Implementation struct {
	create CreateBadge
	update UpdateBadge
	logger tracelog.Logger
}

// NewBadges create new Implementation
func NewBadges(create CreateBadge, update UpdateBadge, logger tracelog.Logger) *Implementation {
	return &Implementation{
		create: create,
		update: update,
		logger: logger,
	}
}

// GetDescription is a simple alias to the ServiceDesc constructor.
// It makes it possible to register the service implementation @ the server.
func (i *Implementation) GetDescription() transport.ServiceDesc {
	return desc.NewBadgesServiceDesc(i)
}
