// Code generated by tron. You must modify it.

package badges

import (
	context "context"

	badgesV1 "github.com/lissteron/cloudsuny/pkg/badges/v1"
	"github.com/lissteron/cloudsuny/pkg/types/v1"
)

func (i *Implementation) Create(
	ctx context.Context,
	req *badgesV1.CreateReq,
) (resp *badgesV1.CreateResp, err error) {
	if err := req.Validate(); err != nil {
		return nil, err
	}

	result, err := i.create.Do(ctx, req.ToDomain())
	if err != nil {
		return nil, err
	}

	resp = &badgesV1.CreateResp{
		Data: types.BadgeFromDomain(result),
	}

	return resp, nil
}
