// Code generated by tron. Place config helpers here.
package config

import (
	"github.com/loghole/database"
	_ "github.com/mattn/go-sqlite3"
	"github.com/spf13/viper"
)

func ImgPath() string {
	return viper.GetString(ImagesPath)
}

func SQLiteConfig() *database.Config {
	return &database.Config{
		Database:     viper.GetString(DatabasePath),
		Type:         database.SQLiteDatabase,
	}
}
