// Code generated by tron v0.9.0. DO NOT EDIT.
package config

const (
	Credentials   = "credentials"
	DatabasePath  = "database_path"
	ImagesPath    = "images_path"
	SessionMaxAge = "session_max_age"
	User1         = "user-1"
)
